SELECT DISTINCT
    c.ITEM_ID,
    c.ITEM_NAME,
    c.RARITY
FROM ITEM_INFO AS p
JOIN ITEM_TREE AS t
ON p.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO AS c
ON t.ITEM_ID = c.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;

