SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = i.FISH_TYPE
)
ORDER BY i.ID ASC;
